#端口号
server:
  port: 8080
#  指定应用的名称（默认是工程名）
spring:
  application:
    name: reggie_take_out
#    数据源的配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: rxq20030705123

  redis:
    host: localhost
    #password: 123456
    port: 6379
    database: 0
#   MybatisPlus的配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#文件存储路径的配置
reggie:
  path: D:\csLearning\riggie_takeout\files\photoes\